# Generated by Django 6.1.1 on 2026-09-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chequing", "Chequing"),
                            ("savings", "Savings"),
                            ("credit_card", "Credit Card"),
                            ("tfsa", "Tfsa"),
                            ("rrsp", "Rrsp"),
                            ("fhsa", "Fhsa"),
                            ("brokerage", "Brokerage"),
                            ("loan", "Loan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="CAD", max_length=3)),
                ("is_liability", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ledger.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("opening_cents", models.BigIntegerField()),
                ("closing_cents", models.BigIntegerField()),
                ("diff_cents", models.BigIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ledger.account"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ledger.institution"
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount_cents", models.BigIntegerField()),
                ("description", models.CharField(max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                            ("contribution", "Contribution"),
                            ("withdrawal", "Withdrawal"),
                            ("dividend", "Dividend"),
                            ("interest", "Interest"),
                            ("fee", "Fee"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="expense",
                        max_length=20,
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=40)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ledger.account"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ledger.importbatch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ledger.category",
                    ),
                ),
            ],
        ),
    ]
